eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

airport-configurations:
  valid-airport-codes:
    - BOM, DUB, DXB, LHR, STN
  nearby-airport-codes-mapping:
      LHR
      - STN
